import type { Metadata } from "next";
import "./globals.css";
import AppClientShell from "@/components/layout/AppClientShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppClientShell>{children}</AppClientShell>
      </body>
    </html>
  );
}
