import type { Metadata } from "next";
import "./globals.css";
import ClientFluentProvider from "@/components/providers/FluentClientProvider";
import { MsalCustomClientProvider } from "@/components/providers/MsalCustomClientProvider";
import MsalClientProvider from "@/components/providers/MsalClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientFluentProvider>
          <MsalClientProvider>
            <MsalCustomClientProvider>{children}</MsalCustomClientProvider>
          </MsalClientProvider>
        </ClientFluentProvider>
      </body>
    </html>
  );
}
